language: objective-c
osx_image: xcode9.1
script:
  - >
    xcodebuild
    -project Synchronized.xcodeproj
    -scheme SynchronizedTests
    -sdk iphonesimulator
    -destination "platform=iOS Simulator,name=iPhone X"
    -quiet
    ONLY_ACTIVE_ARCH=NO
    test

email:
  on_success: change
  on_failure: change
